// <auto-generated />
using AcademyApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcademyApp.DataAccess.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    partial class AcademyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcademyApp.Domain.Domains.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstimatedTime");

                    b.Property<int>("StudentId");

                    b.Property<int>("TimeSpend");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, EstimatedTime = 30, StudentId = 1, TimeSpend = 25, Title = "JavaProject" },
                        new { Id = 2, EstimatedTime = 80, StudentId = 1, TimeSpend = 75, Title = "HrApp" },
                        new { Id = 3, EstimatedTime = 30, StudentId = 2, TimeSpend = 25, Title = "MVCProject" },
                        new { Id = 4, EstimatedTime = 40, StudentId = 2, TimeSpend = 35, Title = "MyProject" },
                        new { Id = 5, EstimatedTime = 50, StudentId = 3, TimeSpend = 45, Title = "JavaScriptProject" },
                        new { Id = 6, EstimatedTime = 60, StudentId = 3, TimeSpend = 55, Title = "C#Project" }
                    );
                });

            modelBuilder.Entity("AcademyApp.Domain.Domains.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("TypeOfAcademy");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new { Id = 1, Age = 25, FirstName = "Bob", LastName = "Bobsky", TypeOfAcademy = 0 },
                        new { Id = 2, Age = 26, FirstName = "Jill", LastName = "Wayne", TypeOfAcademy = 1 },
                        new { Id = 3, Age = 27, FirstName = "John", LastName = "Johnson", TypeOfAcademy = 2 }
                    );
                });

            modelBuilder.Entity("AcademyApp.Domain.Domains.Project", b =>
                {
                    b.HasOne("AcademyApp.Domain.Domains.Student", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
